# Generated by Django 5.2.7 on 2025-11-25 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_education", "0001_initial"),
        ("app_geo", "0001_initial"),
        ("app_taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aulaestudiante",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aulas",
            name="docente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aulaestudiante",
            name="aula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_education.aulas"
            ),
        ),
        migrations.AddField(
            model_name="actividades",
            name="aula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_education.aulas"
            ),
        ),
        migrations.AddField(
            model_name="comentarios",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="fichas",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_taxonomy.categoria",
            ),
        ),
        migrations.AddField(
            model_name="fichas",
            name="especie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_taxonomy.especies",
            ),
        ),
        migrations.AddField(
            model_name="comentarios",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.fichas",
            ),
        ),
        migrations.AddField(
            model_name="aulas",
            name="ficha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.fichas",
            ),
        ),
        migrations.AddField(
            model_name="fichas",
            name="grado_educativo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.gradodeniveleducativo",
            ),
        ),
        migrations.AddField(
            model_name="instituciones",
            name="distrito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_geo.distrito"
            ),
        ),
        migrations.AddField(
            model_name="aulas",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.instituciones",
            ),
        ),
        migrations.AddField(
            model_name="fichas",
            name="nivel_educativo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.niveleducativo",
            ),
        ),
        migrations.AddField(
            model_name="progreso",
            name="actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.actividades",
            ),
        ),
        migrations.AddField(
            model_name="progreso",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="actividades",
            name="tipo_actividad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.tipoactividad",
            ),
        ),
        migrations.AddField(
            model_name="instituciones",
            name="tipo_institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_education.tipoinstitucion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aulaestudiante",
            unique_together={("aula", "estudiante")},
        ),
    ]
