# Generated by Django 5.2.7 on 2025-11-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Juego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="juegos/"),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "lti_client_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
