# Generated by Django 5.2.7 on 2025-11-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_minigames", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("launch_url", models.URLField()),
                ("consumer_key", models.CharField(max_length=200)),
                (
                    "shared_secret",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
