# Generated by Django 5.2.7 on 2025-11-25 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_minigames", "0002_externaltool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="juego",
            name="lti_client_id",
        ),
        migrations.AddField(
            model_name="juego",
            name="external_tool",
            field=models.ForeignKey(
                blank=True,
                help_text="Si está vacío se usará url (iframe).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_minigames.externaltool",
            ),
        ),
        migrations.AddField(
            model_name="juego",
            name="lti_outcome_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="juego",
            name="lti_result_sourcedid",
            field=models.TextField(blank=True, null=True),
        ),
    ]
