# Generated by Django 5.2.7 on 2025-11-25 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_gamification", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="insigniasusuario",
            name="insignia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_gamification.definicioninsignia",
            ),
        ),
        migrations.AddField(
            model_name="insigniasusuario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="juegousuario",
            name="juego",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_gamification.juego"
            ),
        ),
        migrations.AddField(
            model_name="juegousuario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="juego",
            name="nivel_dificultad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_gamification.niveldificultad",
            ),
        ),
        migrations.AddField(
            model_name="juegousuario",
            name="recompensa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_gamification.recompensa",
            ),
        ),
        migrations.AddField(
            model_name="juego",
            name="tipo_juego",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_gamification.tipojuego",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="mision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_gamification.mission",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="UsuarioPuntaje",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rango_avance",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_gamification.rango",
                    ),
                ),
            ],
        ),
    ]
