# Generated by Django 5.2.7 on 2025-11-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distrito", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Avistamientos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_avistamiento", models.DateField()),
                ("comentario", models.CharField(max_length=200)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_taxonomy.especies",
                    ),
                ),
            ],
        ),
    ]
