# Generated by Django 5.2.7 on 2025-10-22 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_usuariopersonalizado_apellido_materno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinicionInsignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('icon_url', models.CharField(max_length=255)),
                ('criterio', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelDificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dificultad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rango', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('icono_url', models.CharField(max_length=255)),
                ('puntos', models.IntegerField(default=0)),
                ('criterio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_juego', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsigniasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gamification.definicioninsignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=100)),
                ('instrucciones', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel_dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gamification.niveldificultad')),
                ('tipo_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gamification.tipojuego')),
            ],
        ),
        migrations.CreateModel(
            name='JuegoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
                ('fecha_jugada', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gamification.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recompensa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gamification.recompensa')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPuntaje',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rango_avance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_gamification.rango')),
            ],
        ),
    ]
