# Generated by Django 5.2.7 on 2025-10-22 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EpocaFloracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoca_floracion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDeConservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_conservacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModoDeReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_de_reproduccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PeligroHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_peligro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_animal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFlor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_flor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproduccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suelo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsosAlimenticios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usos_alimenticios', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsosMedicinales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usos_medicinales', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('epoca_floracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.epocafloracion')),
                ('tipo_flor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.tipoflor')),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.categoria')),
                ('estado_conservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.estadodeconservacion')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.habitat')),
                ('locacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.locacion')),
                ('peligro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.peligrohumano')),
                ('tipo_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.tipoespecie')),
                ('tipo_reproduccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.tiporeproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Usos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('usos_alimenticios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.usosalimenticios')),
                ('usos_medicinales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.usosmedicinales')),
            ],
        ),
        migrations.CreateModel(
            name='Fauna',
            fields=[
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_taxonomy.especies')),
                ('tiempo_gestacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_crias', models.CharField(blank=True, max_length=50, null=True)),
                ('tamano_min_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tamano_max_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_min_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_max_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modo_reproduccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.mododereproduccion')),
                ('tipo_alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.tipoalimentacion')),
                ('tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.tipoanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_taxonomy.especies')),
                ('altura_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('floracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.floracion')),
                ('tipo_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.tipoplanta')),
                ('tipo_suelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.tiposuelo')),
                ('usos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_taxonomy.usos')),
            ],
        ),
    ]
