# Generated by Django 5.2.7 on 2025-11-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_education", "0001_initial"),
        ("app_taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoMultimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_multimedia", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Multimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=512)),
                ("titulo", models.CharField(blank=True, max_length=200, null=True)),
                ("creditos", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "tipo_multimedia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_multimedia.tipomultimedia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichaMultimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_education.fichas",
                    ),
                ),
                (
                    "multimedia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_multimedia.multimedia",
                    ),
                ),
            ],
            options={
                "unique_together": {("ficha", "multimedia")},
            },
        ),
        migrations.CreateModel(
            name="EspecieMultimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_taxonomy.especies",
                    ),
                ),
                (
                    "multimedia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_multimedia.multimedia",
                    ),
                ),
            ],
            options={
                "unique_together": {("especie", "multimedia")},
            },
        ),
    ]
