# Generated by Django 5.1.3 on 2025-12-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpeciesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=200, unique=True)),
                ("filename", models.CharField(max_length=300)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="species/"),
                ),
            ],
        ),
    ]
