# Generated by Django 5.1.3 on 2025-12-03 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userservice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de Sesión"),
                            ("sighting", "Avistamiento Registrado"),
                            ("content_view", "Contenido Visto"),
                            ("badge_earned", "Insignia Ganada"),
                            ("profile_update", "Perfil Actualizado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Actividad de Usuario",
                "verbose_name_plural": "Actividades de Usuarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre Completo"
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Institución Educativa",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Grado"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Sección"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Materia/Curso",
                    ),
                ),
                (
                    "study_area",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Área de Especialidad",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biografía")),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL del Avatar"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="sighting",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Avistamiento",
                "verbose_name_plural": "Avistamientos",
            },
        ),
        migrations.AddField(
            model_name="sighting",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="sighting",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL de Imagen"),
        ),
        migrations.AddField(
            model_name="sighting",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitud",
            ),
        ),
        migrations.AddField(
            model_name="sighting",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitud",
            ),
        ),
        migrations.AddField(
            model_name="sighting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sighting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sightings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="sighting",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("verified", "Verificado"),
                    ("rejected", "Rechazado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado de Verificación",
            ),
        ),
        migrations.AlterField(
            model_name="sighting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="sighting",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Ubicación"),
        ),
        migrations.AlterField(
            model_name="sighting",
            name="species",
            field=models.CharField(max_length=120, verbose_name="Especie"),
        ),
        migrations.AddIndex(
            model_name="sighting",
            index=models.Index(
                fields=["user", "-created_at"], name="userservice_user_id_208c82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sighting",
            index=models.Index(
                fields=["verification_status"], name="userservice_verific_e116ca_idx"
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "-created_at"], name="userservice_user_id_10ac44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type", "-created_at"],
                name="userservice_activit_117a85_idx",
            ),
        ),
    ]
