# Generated by Django 5.1.3 on 2025-12-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0002_institution'),
    ]

    operations = []
