# Generated by Django 5.1.3 on 2025-12-14 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userservice", "0003_useractivity_userprofile_delete_institution_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("type", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("phone", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Título"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitud"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitud"
                    ),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="Imagen")),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("park", "Parque Nacional"),
                            ("trail", "Sendero"),
                            ("waterfall", "Catarata"),
                            ("cave", "Cueva"),
                            ("river", "Río"),
                            ("viewpoint", "Mirador"),
                        ],
                        default="trail",
                        max_length=20,
                        verbose_name="Tipo de Lugar",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("moderate", "Moderado"),
                            ("difficult", "Difícil"),
                        ],
                        default="easy",
                        max_length=20,
                        verbose_name="Dificultad",
                    ),
                ),
                (
                    "visit_count",
                    models.IntegerField(default=0, verbose_name="Número de Visitas"),
                ),
                (
                    "sightings_count",
                    models.IntegerField(
                        default=0, verbose_name="Avistamientos Registrados"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Lugar de Interés",
                "verbose_name_plural": "Lugares de Interés",
                "ordering": ["-visit_count", "title"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Asunto"),
                ),
                ("content", models.TextField(verbose_name="Mensaje")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("personal", "Mensaje Personal"),
                            ("notification", "Notificación del Sistema"),
                            ("feedback", "Retroalimentación de Experto"),
                            ("announcement", "Anuncio de Docente"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Leído")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Lectura"
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archivado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatario",
                    ),
                ),
                (
                    "related_sighting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="userservice.sighting",
                        verbose_name="Avistamiento Relacionado",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "recipient", "-created_at"],
                        name="userservice_sender__ac4877_idx",
                    ),
                    models.Index(
                        fields=["recipient", "read", "-created_at"],
                        name="userservice_recipie_c6e3ab_idx",
                    ),
                    models.Index(
                        fields=["message_type", "-created_at"],
                        name="userservice_message_085e9e_idx",
                    ),
                ],
            },
        ),
    ]
