# Generated by Django 5.1.3 on 2025-12-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0003_place'),
        ('userservice', '0004_institution_place_message'),
    ]

    operations = [
    ]
