# Generated by Django 5.1.3 on 2025-12-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0004_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='userservice_sender__e9ca49_idx',
            old_name='userservic_sender__a6b2f1_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='userservice_recipie_ab42ae_idx',
            old_name='userservic_recipient__c7d1e3_idx',
        ),
    ]
