# Generated by Django 5.1.3 on 2025-12-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0005_merge_0003_place_0004_institution_place_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_encrypted',
            field=models.TextField(blank=True, verbose_name='Correo Encriptado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Correo Verificado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Verificación'),
        ),
    ]
