# Generated by Django 5.1.3 on 2025-12-09 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0005_rename_userservic_sender__a6b2f1_idx_userservice_sender__e9ca49_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='userservice_sender__e9ca49_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='userservice_recipie_ab42ae_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, db_column='recipient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, db_column='sender_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient'], name='userservice_sender__e9ca49_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'read'], name='userservice_recipie_ab42ae_idx'),
        ),
    ]
