
CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS education;
CREATE SCHEMA IF NOT EXISTS games;
CREATE SCHEMA IF NOT EXISTS taxonomy;
CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS geo;

CREATE TABLE admin.Roles (
  IDrol integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  NombreRol varchar(50) NOT NULL
);

CREATE TABLE admin.Usuarios (
  IDusuario integer GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ) PRIMARY KEY,
  Nombres varchar(100) NOT NULL,
  ApellidoPaterno varchar(50) NOT NULL,
  ApellidoMaterno varchar(50) NOT NULL,
  Correo varchar(100) NOT NULL,
  ClaveHash varchar(255) NOT NULL,
  IDrol integer NOT NULL,
  IDnivelEducativo integer NULL,
  IDgradoDeNIvelEducativo integer NULL,
  FechaCreacion timestamptz DEFAULT now() NOT NULL,
  FechaActualizacion timestamptz NULL
);

CREATE TABLE admin.UsuarioPuntaje (
  IDusuario integer PRIMARY KEY,
  IDrangoAvance integer DEFAULT 1 NOT NULL
);


CREATE TABLE education.TipoActividad (
  IDtipoActividad integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  TipoActividad varchar(100) NOT NULL
);

CREATE TABLE education.Aulas (
  IDaula integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  NombreAula varchar(100),
  CodigoAula varchar(20) NOT NULL,
  IDinstitucion integer NOT NULL,
  IDdocente integer NOT NULL,
  FechaCreacion timestamptz DEFAULT now() NOT NULL,
  IDficha integer NULL
);

CREATE TABLE education.AulaEstudiante (
  IDaula integer NOT NULL,
  IDestudiante integer NOT NULL,
  FechaIngreso timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY (IDaula, IDestudiante)
);

CREATE TABLE education.Actividades (
  IDactividad integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  Titulo varchar(100),
  Instrucciones text,
  IDtipoActividad integer NOT NULL,
  IDaula integer NOT NULL
);

CREATE TABLE education.Fichas (
  IDficha integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  Titulo varchar(100),
  Descripcion text,
  IDcategoria integer NULL,
  IDespecie integer NULL,
  IDnivelEducativo integer NOT NULL,
  IDgradoEducativo integer NOT NULL
);

CREATE TABLE education.Comentarios (
  IDcomentario integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  IDusuario integer NOT NULL,
  IDficha integer NULL,
  Comentario varchar(200),
  Fecha timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE education.Progreso (
  IDprogreso integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  IDusuario integer NOT NULL,
  IDactividad integer NOT NULL,
  Fecha timestamptz DEFAULT now() NOT NULL,
  Puntuacion integer NULL,
  Completado boolean DEFAULT false
);

CREATE TABLE education.Instituciones (
  IDinstitucion integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  NombreInstitucion varchar(100) NOT NULL,
  IDdistrito integer NOT NULL,
  IDtipoInstitucion integer NOT NULL,
  Direccion varchar(300) NULL
);

CREATE TABLE education.TipoInstitucion (
  IDtipoInstitucion integer NOT NULL PRIMARY KEY,
  TipoInstitucion varchar(50) NOT NULL
);

CREATE TABLE education.NivelEducativo (
  IDnivelEducativo integer NOT NULL PRIMARY KEY,
  Nivel varchar(20) NOT NULL
);

CREATE TABLE education.GradoDeNIvelEducativo (
  IDgrado integer NOT NULL PRIMARY KEY,
  Grado varchar(50) NOT NULL
);


CREATE TABLE games.NivelDificultad (
  IDnivelDificultad integer NOT NULL PRIMARY KEY,
  NombreDificultad varchar(10) NOT NULL
);

CREATE TABLE games.TipoJuego (
  IDtipoJuego integer NOT NULL PRIMARY KEY,
  TipoJuego varchar(50) NOT NULL
);

CREATE TABLE games.Juego (
  IDjuego integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  NombreJuego varchar(100) NOT NULL,
  IDtipoJuego integer NOT NULL,
  Instrucciones varchar(500) NOT NULL,
  Descripcion varchar(50) NOT NULL,
  IDnivelDificultad integer NOT NULL
);

CREATE TABLE games.JuegoUsuario (
  IDjuegoUsuario integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  IDusuario integer NOT NULL,
  IDjuego integer NOT NULL,
  Puntaje integer NULL,
  FechaJugada timestamptz DEFAULT now() NOT NULL,
  IDrecompensa integer NULL
);

CREATE TABLE games.Recompensa (
  IDrecompensa integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  Codigo varchar(50) NOT NULL,
  Nombre varchar(100) NOT NULL,
  Descripcion varchar(500) NOT NULL,
  IconoURL varchar(255) NOT NULL,
  Puntos integer DEFAULT 0 NOT NULL,
  Criterio text NOT NULL
);

CREATE TABLE games.DefinicionInsignia (
  IDinsignia integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  Titulo varchar(100) NOT NULL,
  Descripcion varchar(500) NOT NULL,
  IconURL varchar(255) NOT NULL,
  Criterio varchar(500) NULL
);

CREATE TABLE games.InsigniasUsuario (
  IDinsigniaUsuario integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  IDusuario integer NOT NULL,
  IDinsignia integer NOT NULL,
  FechaObtenida timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE games.Rango (
  IDrango integer NOT NULL PRIMARY KEY,
  NombreRango varchar(50) NOT NULL
);

CREATE TABLE taxonomy.Categoria (
  IDcategoria integer NOT NULL PRIMARY KEY,
  Categoria varchar(20) NOT NULL
);

CREATE TABLE taxonomy.EstadoDeConservacion (
  IDestadoConservacion integer NOT NULL PRIMARY KEY,
  EstadoConservacion varchar(20)
);

CREATE TABLE taxonomy.Habitat (
  IDhabitat integer NOT NULL PRIMARY KEY,
  Habitat varchar(50)
);

CREATE TABLE taxonomy.Locacion (
  IDlocacion integer NOT NULL PRIMARY KEY,
  Locacion varchar(200) NOT NULL
);

CREATE TABLE taxonomy.PeligroHumano (
  IDpeligro integer NOT NULL PRIMARY KEY,
  NivelPeligro varchar(50)
);

CREATE TABLE taxonomy.TipoEspecie (
  IDtipoEspecie integer NOT NULL PRIMARY KEY,
  Especie varchar(50) NOT NULL
);

CREATE TABLE taxonomy.TipoPlanta (
  IDtipoPlanta integer NOT NULL PRIMARY KEY,
  Tipo varchar(50) NOT NULL,
  Descripcion varchar(200) NOT NULL
);

CREATE TABLE taxonomy.TipoAnimal (
  IDtipoAnimal integer NOT NULL PRIMARY KEY,
  TipoAnimal varchar(50)
);

CREATE TABLE taxonomy.TipoAlimentacion (
  IDtipoAlimentacion integer NOT NULL PRIMARY KEY,
  Alimentacion varchar(20) NOT NULL
);

CREATE TABLE taxonomy.TipoReproduccion (
  IDtipoReproduccion integer NOT NULL PRIMARY KEY,
  Reproduccion varchar(20) NOT NULL
);

CREATE TABLE taxonomy.Floracion (
  IDfloracion integer NOT NULL PRIMARY KEY,
  IDepocaFloracion integer NULL,
  IDtipoFlor integer NULL,
  Descripcion varchar(200) NULL
);

CREATE TABLE taxonomy.EpocaFloracion (
  IDepocaFloracion integer NOT NULL PRIMARY KEY,
  EpocaFloracion varchar(20) NOT NULL
);

CREATE TABLE taxonomy.TipoFlor (
  IDtipoFlor integer NOT NULL PRIMARY KEY,
  TipoFlor varchar(50) NOT NULL
);

CREATE TABLE taxonomy.TipoSuelo (
  IDtipoSuelo integer NOT NULL PRIMARY KEY,
  Suelo char(10) NOT NULL
);

CREATE TABLE taxonomy.UsosAlimenticios (
  IDusosAlimneticios integer NOT NULL PRIMARY KEY,
  UsosAlimenticios char(10) NULL
);

CREATE TABLE taxonomy.UsosMedicinales (
  IDusosMedicinales integer NOT NULL PRIMARY KEY,
  UsosMedicinales char(10) NULL
);

CREATE TABLE taxonomy.Usos (
  IDusos integer NOT NULL PRIMARY KEY,
  IDusosAlimenticios integer NULL,
  IDusosMedicinales integer NULL,
  Descripcion varchar(200) NULL
);

CREATE TABLE taxonomy.Especies (
  IDespecie integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  IDcategoria integer NOT NULL,
  IDtipoEspecie integer NOT NULL,
  NombreComun varchar(100) NOT NULL,
  NombreCientifico varchar(100) NOT NULL,
  Descripcion varchar(500) NOT NULL,
  IDhabitat integer NOT NULL,
  IDlocacion integer NOT NULL,
  IDtipoReproduccion integer NOT NULL,
  IDestadoConservacion integer NOT NULL,
  IDpeligro integer NOT NULL
);

CREATE TABLE taxonomy.Flora (
  IDespecie integer NOT NULL PRIMARY KEY,
  IDtipoPlanta integer NOT NULL,
  AlturaMaxima numeric(5,2) NULL,
  IDfloracion integer NULL,
  IDtipoSuelo integer NOT NULL,
  IDusos integer NULL
);

CREATE TABLE taxonomy.Fauna (
  IDespecie integer NOT NULL PRIMARY KEY,
  IDtipoAnimal integer NOT NULL,
  IDtipoAlimentacion integer NOT NULL,
  IDmodoReproduccion integer NULL,
  TiempoGestacion varchar(50) NULL,
  NumeroCrias varchar(50) NULL,
  TamanoMin_cm numeric(10,2) NULL,
  TamanoMax_cm numeric(10,2) NULL,
  PesoMin_kg numeric(10,2) NULL,
  PesoMax_kg numeric(10,2) NULL
);

CREATE TABLE taxonomy.ModoDeReproduccion (
  IDmodoReproduccion integer NOT NULL PRIMARY KEY,
  ModoDeReproduccion varchar(50) NOT NULL
);


CREATE TABLE media.TipoMultimedia (
  IDTipoMultimedia integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  TipoMultimedia varchar(100) NOT NULL
);

CREATE TABLE media.Multimedia (
  IDmultimedia integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  IDtipoMultimedia integer NOT NULL,
  URL varchar(512) NOT NULL,
  Titulo varchar(200) NULL,
  Creditos varchar(200) NULL
);

CREATE TABLE media.EspecieMultimedia (
  IDespecie integer NOT NULL,
  IDmultimedia integer NOT NULL,
  PRIMARY KEY (IDespecie, IDmultimedia)
);

CREATE TABLE media.FichaMultimedia (
  IDficha integer NOT NULL,
  IDmultimedia integer NOT NULL,
  PRIMARY KEY (IDficha, IDmultimedia)
);

CREATE TABLE geo.Distrito (
  IDdistrito integer NOT NULL PRIMARY KEY,
  Distrito varchar(20) NOT NULL
);

CREATE TABLE geo.Avistamientos (
  IDavistamiento integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  IDusuario integer NOT NULL,
  IDespecie integer NOT NULL,
  FechaAvistamiento date NOT NULL,
  Comentario varchar(200) NOT NULL,
  Latitud numeric(9,6) NOT NULL,
  Longitud numeric(9,6) NOT NULL
);

CREATE UNIQUE INDEX ux_roles_nombre ON admin.Roles (NombreRol);
CREATE UNIQUE INDEX ux_usuarios_correo ON admin.Usuarios (Correo);
CREATE UNIQUE INDEX ux_aulas_codigoaula ON education.Aulas (CodigoAula);
CREATE UNIQUE INDEX ux_recompensa_codigo ON games.Recompensa (Codigo);

ALTER TABLE admin.Usuarios
  ADD CONSTRAINT fk_usuarios_rol FOREIGN KEY (IDrol) REFERENCES admin.Roles (IDrol) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_usuarios_niveleducativo FOREIGN KEY (IDnivelEducativo) REFERENCES education.NivelEducativo (IDnivelEducativo) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_usuarios_gradoeducativo FOREIGN KEY (IDgradoDeNIvelEducativo) REFERENCES education.GradoDeNIvelEducativo (IDgrado) ON DELETE NO ACTION;


ALTER TABLE admin.UsuarioPuntaje
  ADD CONSTRAINT fk_usuariopuntaje_usuario FOREIGN KEY (IDusuario) REFERENCES admin.Usuarios (IDusuario) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_usuariopuntaje_rango FOREIGN KEY (IDrangoAvance) REFERENCES games.Rango (IDrango) ON DELETE NO ACTION;


ALTER TABLE education.Actividades
  ADD CONSTRAINT fk_actividades_aula FOREIGN KEY (IDaula) REFERENCES education.Aulas (IDaula) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_actividades_tipoactividad FOREIGN KEY (IDtipoActividad) REFERENCES education.TipoActividad (IDtipoActividad) ON DELETE NO ACTION;


ALTER TABLE education.AulaEstudiante
  ADD CONSTRAINT fk_aulaestudiante_aula FOREIGN KEY (IDaula) REFERENCES education.Aulas (IDaula) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_aulaestudiante_estudiante FOREIGN KEY (IDestudiante) REFERENCES admin.Usuarios (IDusuario) ON DELETE NO ACTION;


ALTER TABLE education.Aulas
  ADD CONSTRAINT fk_aulas_docente FOREIGN KEY (IDdocente) REFERENCES admin.Usuarios (IDusuario) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_aulas_institucion FOREIGN KEY (IDinstitucion) REFERENCES education.Instituciones (IDinstitucion) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_aulas_ficha FOREIGN KEY (IDficha) REFERENCES education.Fichas (IDficha) ON DELETE NO ACTION;


ALTER TABLE geo.Avistamientos
  ADD CONSTRAINT fk_avistamientos_especie FOREIGN KEY (IDespecie) REFERENCES taxonomy.Especies (IDespecie) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_avistamientos_usuario FOREIGN KEY (IDusuario) REFERENCES admin.Usuarios (IDusuario) ON DELETE NO ACTION;


ALTER TABLE education.Comentarios
  ADD CONSTRAINT fk_comentarios_ficha FOREIGN KEY (IDficha) REFERENCES education.Fichas (IDficha) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_comentarios_usuario FOREIGN KEY (IDusuario) REFERENCES admin.Usuarios (IDusuario) ON DELETE NO ACTION;


ALTER TABLE media.EspecieMultimedia
  ADD CONSTRAINT fk_especiemultimedia_especie FOREIGN KEY (IDespecie) REFERENCES taxonomy.Especies (IDespecie) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_especiemultimedia_multimedia FOREIGN KEY (IDmultimedia) REFERENCES media.Multimedia (IDmultimedia) ON DELETE NO ACTION;

ALTER TABLE taxonomy.Especies
  ADD CONSTRAINT fk_especies_categoria FOREIGN KEY (IDcategoria) REFERENCES taxonomy.Categoria (IDcategoria) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_especies_estado FOREIGN KEY (IDestadoConservacion) REFERENCES taxonomy.EstadoDeConservacion (IDestadoConservacion) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_especies_habitat FOREIGN KEY (IDhabitat) REFERENCES taxonomy.Habitat (IDhabitat) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_especies_locacion FOREIGN KEY (IDlocacion) REFERENCES taxonomy.Locacion (IDlocacion) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_especies_peligro FOREIGN KEY (IDpeligro) REFERENCES taxonomy.PeligroHumano (IDpeligro) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_especies_tipoespecie FOREIGN KEY (IDtipoEspecie) REFERENCES taxonomy.TipoEspecie (IDtipoEspecie) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_especies_tiporeproduccion FOREIGN KEY (IDtipoReproduccion) REFERENCES taxonomy.TipoReproduccion (IDtipoReproduccion) ON DELETE NO ACTION;


ALTER TABLE taxonomy.Fauna
  ADD CONSTRAINT fk_fauna_especie FOREIGN KEY (IDespecie) REFERENCES taxonomy.Especies (IDespecie) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_fauna_modorepro FOREIGN KEY (IDmodoReproduccion) REFERENCES taxonomy.ModoDeReproduccion (IDmodoReproduccion) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_fauna_tipoalimentacion FOREIGN KEY (IDtipoAlimentacion) REFERENCES taxonomy.TipoAlimentacion (IDtipoAlimentacion) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_fauna_tipoanimal FOREIGN KEY (IDtipoAnimal) REFERENCES taxonomy.TipoAnimal (IDtipoAnimal) ON DELETE NO ACTION;


ALTER TABLE media.FichaMultimedia
  ADD CONSTRAINT fk_fichamultimedia_ficha FOREIGN KEY (IDficha) REFERENCES education.Fichas (IDficha) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_fichamultimedia_multimedia FOREIGN KEY (IDmultimedia) REFERENCES media.Multimedia (IDmultimedia) ON DELETE NO ACTION;

ALTER TABLE education.Fichas
  ADD CONSTRAINT fk_fichas_especie FOREIGN KEY (IDespecie) REFERENCES taxonomy.Especies (IDespecie) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_fichas_categoria FOREIGN KEY (IDcategoria) REFERENCES taxonomy.Categoria (IDcategoria) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_fichas_grado FOREIGN KEY (IDgradoEducativo) REFERENCES education.GradoDeNIvelEducativo (IDgrado) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_fichas_nivel FOREIGN KEY (IDnivelEducativo) REFERENCES education.NivelEducativo (IDnivelEducativo) ON DELETE NO ACTION;

ALTER TABLE games.Juego
  ADD CONSTRAINT fk_juego_niveldificultad FOREIGN KEY (IDnivelDificultad) REFERENCES games.NivelDificultad (IDnivelDificultad) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_juego_tipjuego FOREIGN KEY (IDtipoJuego) REFERENCES games.TipoJuego (IDtipoJuego) ON DELETE NO ACTION;


ALTER TABLE games.JuegoUsuario
  ADD CONSTRAINT fk_juegousuario_juego FOREIGN KEY (IDjuego) REFERENCES games.Juego (IDjuego) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_juegousuario_usuario FOREIGN KEY (IDusuario) REFERENCES admin.Usuarios (IDusuario) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_juegousuario_recompensa FOREIGN KEY (IDrecompensa) REFERENCES games.Recompensa (IDrecompensa) ON DELETE NO ACTION;

ALTER TABLE media.Multimedia
  ADD CONSTRAINT fk_multimedia_tipomult FOREIGN KEY (IDtipoMultimedia) REFERENCES media.TipoMultimedia (IDTipoMultimedia) ON DELETE NO ACTION;

ALTER TABLE education.Progreso
  ADD CONSTRAINT fk_progreso_actividad FOREIGN KEY (IDactividad) REFERENCES education.Actividades (IDactividad) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_progreso_usuario FOREIGN KEY (IDusuario) REFERENCES admin.Usuarios (IDusuario) ON DELETE NO ACTION;

ALTER TABLE games.InsigniasUsuario
  ADD CONSTRAINT fk_insigniasusuario_usuario FOREIGN KEY (IDusuario) REFERENCES admin.Usuarios (IDusuario) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_insigniasusuario_definicion FOREIGN KEY (IDinsignia) REFERENCES games.DefinicionInsignia (IDinsignia) ON DELETE NO ACTION;

ALTER TABLE education.Instituciones
  ADD CONSTRAINT fk_instituciones_distrito FOREIGN KEY (IDdistrito) REFERENCES geo.Distrito (IDdistrito) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_instituciones_tipoinstitucion FOREIGN KEY (IDtipoInstitucion) REFERENCES education.TipoInstitucion (IDtipoInstitucion) ON DELETE NO ACTION;


ALTER TABLE taxonomy.Flora
  ADD CONSTRAINT fk_flora_especie FOREIGN KEY (IDespecie) REFERENCES taxonomy.Especies (IDespecie) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_flora_floracion FOREIGN KEY (IDfloracion) REFERENCES taxonomy.Floracion (IDfloracion) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_flora_tiposuelo FOREIGN KEY (IDtipoSuelo) REFERENCES taxonomy.TipoSuelo (IDtipoSuelo) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_flora_usos FOREIGN KEY (IDusos) REFERENCES taxonomy.Usos (IDusos) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_flora_tipoplanta FOREIGN KEY (IDtipoPlanta) REFERENCES taxonomy.TipoPlanta (IDtipoPlanta) ON DELETE NO ACTION;

ALTER TABLE taxonomy.Floracion
  ADD CONSTRAINT fk_floracion_epoca FOREIGN KEY (IDepocaFloracion) REFERENCES taxonomy.EpocaFloracion (IDepocaFloracion) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_floracion_tipoflor FOREIGN KEY (IDtipoFlor) REFERENCES taxonomy.TipoFlor (IDtipoFlor) ON DELETE NO ACTION;

ALTER TABLE taxonomy.Usos
  ADD CONSTRAINT fk_usos_alimenticios FOREIGN KEY (IDusosAlimenticios) REFERENCES taxonomy.UsosAlimenticios (IDusosAlimneticios) ON DELETE NO ACTION,
  ADD CONSTRAINT fk_usos_medicinales FOREIGN KEY (IDusosMedicinales) REFERENCES taxonomy.UsosMedicinales (IDusosMedicinales) ON DELETE NO ACTION;


CREATE INDEX idx_usuarios_rol ON admin.Usuarios(IDrol);


CREATE INDEX idx_aulas_institucion ON education.Aulas(IDinstitucion);
CREATE INDEX idx_aulas_docente ON education.Aulas(IDdocente);
CREATE INDEX idx_aulas_ficha ON education.Aulas(IDficha);


CREATE INDEX idx_fichas_especie ON education.Fichas(IDespecie);
CREATE INDEX idx_fichas_categoria ON education.Fichas(IDcategoria);
CREATE INDEX idx_fichas_niveleducativo ON education.Fichas(IDnivelEducativo);
CREATE INDEX idx_fichas_gradoeducativo ON education.Fichas(IDgradoEducativo);


CREATE INDEX idx_progreso_usuario ON education.Progreso(IDusuario);
CREATE INDEX idx_progreso_actividad ON education.Progreso(IDactividad);


CREATE INDEX idx_especies_categoria ON taxonomy.Especies(IDcategoria);
CREATE INDEX idx_especies_tipo ON taxonomy.Especies(IDtipoEspecie);
CREATE INDEX idx_especies_habitat ON taxonomy.Especies(IDhabitat);
CREATE INDEX idx_especies_locacion ON taxonomy.Especies(IDlocacion);
CREATE INDEX idx_especies_conservacion ON taxonomy.Especies(IDestadoConservacion);


CREATE INDEX idx_juego_usuario_usuario ON games.JuegoUsuario(IDusuario);
CREATE INDEX idx_juego_usuario_juego ON games.JuegoUsuario(IDjuego);


CREATE INDEX idx_insignias_usuario ON games.InsigniasUsuario(IDusuario);


CREATE INDEX idx_avistamientos_usuario ON geo.Avistamientos(IDusuario);
CREATE INDEX idx_avistamientos_especie ON geo.Avistamientos(IDespecie);
CREATE INDEX idx_avistamientos_fecha ON geo.Avistamientos(FechaAvistamiento);


CREATE INDEX idx_comentarios_usuario ON education.Comentarios(IDusuario);
CREATE INDEX idx_comentarios_ficha ON education.Comentarios(IDficha);
